
# GET ALL USERS
GET http://localhost:5000/users

###

# GET A SINGLE USER
GET http://localhost:5000/users/2

###

# REGISTER A USER
POST http://localhost:5000/register
content-type: application/json

{
    "email": "mphanyamohau28@gmail.com",
    "password": "dummypassword"
}
###

# LOGIN A USER
POST http://localhost:5000/login
content-type: application/json

{
    "email": "mphanyamohau28@gmail.com",
    "password": "dummypassword"
}
###

###BOOKINGS
http://localhost:5000/bookings

###

### LISTINGS
http://localhost:5000/listings

###

# POST http://localhost:5000/posts 
# content-type: application/json

# {
#     "title": "AirBnB Clone",
#     "author": "Mohau"
#   }